spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mytutor
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG+